name: turn_gen
description: A package that simplifies the generation of additional features
version: 0.0.2
maintainer: Dmitriy Trofimov
homepage: https://github.com/a-dev-mobile/turn_gen
repository: https://github.com/a-dev-mobile/turn_gen/
issue_tracker: https://github.com/a-dev-mobile/turn_gen/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  path: ^1.8.0
  args: ^2.4.0
  cli_util: ^0.3.5
  yaml: ^3.1.1 
  intl: ^0.18.0
  meta: ^1.3.0

dev_dependencies:
  # Analyzer extensions
  dart_code_metrics: ^5.6.0
  very_good_analysis: ^4.0.0+1


turn_gen:
  assets_output: "lib/gen/"
