name: turn_gen
description: TurnGen is a set of scripts combined into a command line tool to minimize coding and simplify various tasks
version: 0.9.2
maintainer: Dmitriy Trofimov
homepage: https://github.com/a-dev-mobile/turn_gen
repository: https://github.com/a-dev-mobile/turn_gen/
issue_tracker: https://github.com/a-dev-mobile/turn_gen/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  path: ^1.8.0
  args: ^2.4.1
  cli_util: ^0.4.0
  yaml: ^3.1.2
  collection: ^1.17.2
  # meta: ^1.9.1
dev_dependencies:
  # Analyzer extensions
  dart_code_metrics: ^5.7.3
  test: ^1.24.2
  very_good_analysis: ^4.0.0+1

turn_gen:
  # assets_output: "lib/gen/"
  # show_method_comments: true
  folder_barrel: lib\steps, lib\core
